In [1]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [4]:
import cv2
from scipy.ndimage import gaussian_filter
import numpy as np

In [2]:
help(cv2.GaussianBlur)

Help on built-in function GaussianBlur:

GaussianBlur(...)
    GaussianBlur(src, ksize, sigmaX[, dst[, sigmaY[, borderType]]]) -> dst
    .   @brief Blurs an image using a Gaussian filter.
    .   
    .   The function convolves the source image with the specified Gaussian kernel. In-place filtering is
    .   supported.
    .   
    .   @param src input image; the image can have any number of channels, which are processed
    .   independently, but the depth should be CV_8U, CV_16U, CV_16S, CV_32F or CV_64F.
    .   @param dst output image of the same size and type as src.
    .   @param ksize Gaussian kernel size. ksize.width and ksize.height can differ but they both must be
    .   positive and odd. Or, they can be zero's and then they are computed from sigma.
    .   @param sigmaX Gaussian kernel standard deviation in X direction.
    .   @param sigmaY Gaussian kernel standard deviation in Y direction; if sigmaY is zero, it is set to be
    .   equal to sigmaX, if both sigmas are z

$G_i= \alpha *e^{-(i-( \texttt{ksize} -1)/2)^2/(2* \texttt{sigma}^2)}$

In [9]:
A = np.arange(24,step=2)
B = A.reshape((3, A.size//3))
print(A)
print(B)

[ 0  2  4  6  8 10 12 14 16 18 20 22]
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [19]:
cv2.GaussianBlur(B, (3,3), 0)

error: OpenCV(4.4.0) /tmp/pip-req-build-civioau0/opencv/modules/imgproc/src/filter.simd.hpp:2922: error: (-213:The function/feature is not implemented) Unsupported combination of source format (=4), and buffer format (=5) in function 'getLinearRowFilter'


In [24]:
cv2.getGaussianKernel(3,1)

array([[0.27406862],
       [0.45186276],
       [0.27406862]])

In [27]:
help(cv2.sepFilter2D)

Help on built-in function sepFilter2D:

sepFilter2D(...)
    sepFilter2D(src, ddepth, kernelX, kernelY[, dst[, anchor[, delta[, borderType]]]]) -> dst
    .   @brief Applies a separable linear filter to an image.
    .   
    .   The function applies a separable linear filter to the image. That is, first, every row of src is
    .   filtered with the 1D kernel kernelX. Then, every column of the result is filtered with the 1D
    .   kernel kernelY. The final result shifted by delta is stored in dst .
    .   
    .   @param src Source image.
    .   @param dst Destination image of the same size and the same number of channels as src .
    .   @param ddepth Destination image depth, see @ref filter_depths "combinations"
    .   @param kernelX Coefficients for filtering each row.
    .   @param kernelY Coefficients for filtering each column.
    .   @param anchor Anchor position within the kernel. The default value \f$(-1,-1)\f$ means that the anchor
    .   is at the kernel center.
    .

In [18]:
cv2.GaussianBlur(B, (3,3), 2.0, 2.0)

error: OpenCV(4.4.0) /tmp/pip-req-build-civioau0/opencv/modules/imgproc/src/filter.simd.hpp:2922: error: (-213:The function/feature is not implemented) Unsupported combination of source format (=4), and buffer format (=5) in function 'getLinearRowFilter'


In [28]:
help(gaussian_filter)

Help on function gaussian_filter in module scipy.ndimage.filters:

gaussian_filter(input, sigma, order=0, output=None, mode='reflect', cval=0.0, truncate=4.0)
    Multidimensional Gaussian filter.
    
    Parameters
    ----------
    input : array_like
        The input array.
    sigma : scalar or sequence of scalars
        Standard deviation for Gaussian kernel. The standard
        deviations of the Gaussian filter are given for each axis as a
        sequence, or as a single number, in which case it is equal for
        all axes.
    order : int or sequence of ints, optional
        The order of the filter along each axis is given as a sequence
        of integers, or as a single number.  An order of 0 corresponds
        to convolution with a Gaussian kernel. A positive order
        corresponds to convolution with that derivative of a Gaussian.
    output : array or dtype, optional
        The array in which to place the output, or the dtype of the
        returned array. By d

In [29]:
B

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [34]:
C = np.arange(5*7).reshape((5,7))
C

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [35]:
gaussian_filter(C, 1)

array([[ 2,  3,  4,  5,  5,  6,  7],
       [ 7,  8,  9, 10, 10, 11, 12],
       [14, 15, 16, 17, 17, 18, 19],
       [20, 21, 22, 23, 23, 24, 25],
       [25, 26, 27, 28, 28, 29, 30]])

In [36]:
gaussian_filter(C, 1, mode="constant", cval=0)

array([[ 1,  2,  3,  4,  4,  5,  4],
       [ 5,  7,  8,  9, 10, 11,  8],
       [ 9, 13, 14, 15, 16, 16, 12],
       [12, 18, 19, 20, 21, 21, 16],
       [11, 16, 17, 18, 19, 18, 14]])

In [37]:
gaussian_filter(C, 1, mode="constant", cval=0, truncate=3)

array([[ 1,  2,  3,  4,  4,  5,  4],
       [ 5,  7,  8, 10, 10, 11,  8],
       [ 9, 13, 14, 16, 16, 16, 12],
       [12, 18, 19, 21, 21, 21, 16],
       [11, 16, 17, 18, 19, 18, 14]])

In [38]:
gaussian_filter(C, 1, mode="constant", cval=0, truncate=2)

array([[ 1,  2,  3,  4,  4,  4,  3],
       [ 5,  7,  9, 10, 11, 11,  8],
       [ 9, 14, 15, 17, 18, 17, 13],
       [13, 18, 20, 21, 22, 21, 16],
       [11, 16, 18, 18, 19, 18, 14]])

In [39]:
gaussian_filter(C.astype(np.float32), 1, mode="constant", cval=0)

array([[ 2.0356565,  3.1410956,  3.9370964,  4.6436644,  5.310304 ,
         5.6047373,  4.4623065],
       [ 5.5451818,  8.003411 ,  9.291193 , 10.259292 , 11.139177 ,
        11.318841 ,  8.81083  ],
       [10.063647 , 14.113399 , 15.795218 , 16.840258 , 17.740498 ,
        17.603382 , 13.501228 ],
       [13.575426 , 18.811594 , 20.719217 , 21.73666  , 22.567202 ,
        22.127024 , 16.841074 ],
       [12.172557 , 16.7847   , 18.363153 , 19.13201  , 19.73636  ,
        19.248343 , 14.599208 ]], dtype=float32)

In [40]:
gaussian_filter(C.astype(np.float32), 1, mode="constant", cval=0, truncate=3)

array([[ 2.0333602,  3.1382968,  3.9343019,  4.642001 ,  5.308544 ,
         5.6031613,  4.461033 ],
       [ 5.5466514,  8.006071 ,  9.294416 , 10.264786 , 11.144147 ,
        11.32378  ,  8.814301 ],
       [10.0666485, 14.118436 , 15.8010235, 16.849276 , 17.748142 ,
        17.61082  , 13.506336 ],
       [13.5796585, 18.818504 , 20.727024 , 21.7483   , 22.576756 ,
        22.136215 , 16.847307 ],
       [12.176372 , 16.790798 , 18.369875 , 19.141853 , 19.744118 ,
        19.255661 , 14.604044 ]], dtype=float32)

In [41]:
gaussian_filter(C.astype(np.float32), 1, mode="constant", cval=0, truncate=2)

array([[ 1.9815019,  3.0770648,  3.874871 ,  4.576181 ,  5.277491 ,
         5.576597 ,  4.4371405],
       [ 5.510598 ,  7.976248 ,  9.272444 , 10.217955 , 11.163466 ,
        11.346136 ,  8.821309 ],
       [10.171518 , 14.291647 , 16.       , 17.       , 18.       ,
        17.855738 , 13.67302  ],
       [13.723973 , 19.049582 , 20.98392  , 21.92943  , 22.87494  ,
        22.419468 , 17.034683 ],
       [12.285273 , 16.968685 , 18.567049 , 19.268358 , 19.969667 ,
        19.468216 , 14.740911 ]], dtype=float32)

In [42]:
gaussian_filter(C.astype(np.float32), 1, mode="constant", cval=0, truncate=1)

array([[ 1.5916401,  2.6444118,  3.3703432,  4.0962744,  4.822206 ,
         5.548137 ,  4.3555884],
       [ 5.3555884,  8.       ,  9.       , 10.       , 11.       ,
        12.       ,  9.163039 ],
       [10.437108 , 15.       , 16.       , 17.       , 18.       ,
        19.       , 14.244559 ],
       [15.518627 , 22.       , 23.       , 24.       , 25.       ,
        26.       , 19.326078 ],
       [13.561608 , 19.13353  , 19.85946  , 20.585392 , 21.311323 ,
        22.037254 , 16.325556 ]], dtype=float32)

In [43]:
gaussian_filter(C.astype(np.float32), 1, mode="constant", cval=0, truncate=0)

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12., 13.],
       [14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27.],
       [28., 29., 30., 31., 32., 33., 34.]], dtype=float32)

In [46]:
D = np.zeros((4,3), dtype=np.float32)
D[1,1] = -1
D

array([[ 0.,  0.,  0.],
       [ 0., -1.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]], dtype=float32)

In [47]:
gaussian_filter(D, 1, mode="constant", cval=0, truncate=1)

array([[-0.07511361, -0.1238414 , -0.07511361],
       [-0.1238414 , -0.20417996, -0.1238414 ],
       [-0.07511361, -0.1238414 , -0.07511361],
       [ 0.        ,  0.        ,  0.        ]], dtype=float32)

In [2]:
import sys
import numpy as np
#import pandas as pd
import datetime
import json
from array import *
import os
import math
from random import randrange
import random

#from keras.models import Sequential
#from keras.models import model_from_json
#from keras.layers import Dense, Activation
#from keras import optimizers
from tensorflow.keras.models import Sequential
from tensorflow.keras.models import model_from_json
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras import optimizers

import tensorflow.keras as keras

import tensorflow.compat.v1 as tf
from tensorflow.compat.v1.keras import backend as K
tf.disable_v2_behavior()

import constants

/home/phunc20/.virtualenvs/rlcomp2020/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/phunc20/.virtualenvs/rlcomp2020/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/phunc20/.virtualenvs/rlcomp2020/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/phunc20/.virtualenvs/rlcomp2020

Instructions for updating:
non-resource variables are not supported in the long term


/home/phunc20/.virtualenvs/rlcomp2020/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/phunc20/.virtualenvs/rlcomp2020/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/phunc20/.virtualenvs/rlcomp2020/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/phunc20/.v

In [3]:
#Classes in GAME_SOCKET_DUMMY.py
class ObstacleInfo:
    # initial energy for obstacles: Land (key = 0): -1, Forest(key = -1): 0 (random), Trap(key = -2): -10, Swamp (key = -3): -5
    types = {0: -1, -1: 0, -2: -10, -3: -5}

    def __init__(self):
        self.type = 0
        self.posx = 0
        self.posy = 0
        self.value = 0
        
class GoldInfo:
    def __init__(self):
        self.posx = 0
        self.posy = 0
        self.amount = 0

    def loads(self, data):
        golds = []
        for gd in data:
            g = GoldInfo()
            g.posx = gd["posx"]
            g.posy = gd["posy"]
            g.amount = gd["amount"]
            golds.append(g)
        return golds

class PlayerInfo:
    STATUS_PLAYING = 0
    STATUS_ELIMINATED_WENT_OUT_MAP = 1
    STATUS_ELIMINATED_OUT_OF_ENERGY = 2
    STATUS_ELIMINATED_INVALID_ACTION = 3
    STATUS_STOP_EMPTY_GOLD = 4
    STATUS_STOP_END_STEP = 5

    def __init__(self, id):
        self.playerId = id
        self.score = 0
        self.energy = 0
        self.posx = 0
        self.posy = 0
        self.lastAction = -1
        self.status = PlayerInfo.STATUS_PLAYING
        self.freeCount = 0

class GameInfo:
    def __init__(self):
        self.numberOfPlayers = 1
        self.width = 0
        self.height = 0
        self.steps = 100
        self.golds = []
        self.obstacles = []

    def loads(self, data):
        m = GameInfo()
        m.width = data["width"]
        m.height = data["height"]
        m.golds = GoldInfo().loads(data["golds"])
        m.obstacles = data["obstacles"]
        m.numberOfPlayers = data["numberOfPlayers"]
        m.steps = data["steps"]
        return m

class UserMatch:
    def __init__(self):
        self.playerId = 1
        self.posx = 0
        self.posy = 0
        self.energy = 50
        self.gameinfo = GameInfo()

    def to_json(self):
        return json.dumps(self, default=lambda o: o.__dict__, sort_keys=True, indent=4)

class StepState:
    def __init__(self):
        self.players = []
        self.golds = []
        self.changedObstacles = []

    def to_json(self):
        return json.dumps(self, default=lambda o: o.__dict__, sort_keys=True, indent=4)


In [4]:
#Main class in GAME_SOCKET_DUMMY.py
class GameSocket:
    bog_energy_chain = {-5: -20, -20: -40, -40: -100, -100: -100}

    def __init__(self):
        self.stepCount = 0
        self.maxStep = 0
        self.mapdir = "Maps"  # where to load all pre-defined maps
        self.mapid = ""
        self.userMatch = UserMatch()
        self.user = PlayerInfo(1)
        self.stepState = StepState()
        self.maps = {}  # key: map file name, value: file content
        self.map = []  # running map info: 0->Land, -1->Forest, -2->Trap, -3:Swamp, >0:Gold
        self.energyOnMap = []  # self.energyOnMap[x][y]: <0, amount of energy which player will consume if it move into (x,y)
        self.E = 50
        self.resetFlag = True
        self.craftUsers = []  # players that craft at current step - for calculating amount of gold
        self.bots = []
        self.craftMap = {}  # cells that players craft at current step, key: x_y, value: number of players that craft at (x,y)

    def init_bots(self):
        self.bots = [Bot1(2), Bot2(3), Bot3(4)]  # use bot1(id=2), bot2(id=3), bot3(id=4)
        #for (bot) in self.bots:  # at the beginning, all bots will have same position, energy as player
        for bot in self.bots:  # at the beginning, all bots will have same position, energy as player
            bot.info.posx = self.user.posx
            bot.info.posy = self.user.posy
            bot.info.energy = self.user.energy
            bot.info.lastAction = -1
            bot.info.status = PlayerInfo.STATUS_PLAYING
            bot.info.score = 0
            self.stepState.players.append(bot.info)
        self.userMatch.gameinfo.numberOfPlayers = len(self.stepState.players)
        #print("numberOfPlayers: ", self.userMatch.gameinfo.numberOfPlayers)

    def reset(self, requests):  # load new game by given request: [map id (filename), posx, posy, initial energy]
        # load new map
        self.reset_map(requests[0])
        self.userMatch.posx = int(requests[1])
        self.userMatch.posy = int(requests[2])
        self.userMatch.energy = int(requests[3])
        self.userMatch.gameinfo.steps = int(requests[4])
        self.maxStep = self.userMatch.gameinfo.steps

        # init data for players
        self.user.posx = self.userMatch.posx  # in
        self.user.posy = self.userMatch.posy
        self.user.energy = self.userMatch.energy
        self.user.status = PlayerInfo.STATUS_PLAYING
        self.user.score = 0
        self.stepState.players = [self.user]
        self.E = self.userMatch.energy
        self.resetFlag = True
        self.init_bots()
        self.stepCount = 0

    def reset_map(self, id):  # load map info
        self.mapId = id
        self.map = json.loads(self.maps[self.mapId])
        self.userMatch = self.map_info(self.map)
        self.stepState.golds = self.userMatch.gameinfo.golds
        self.map = json.loads(self.maps[self.mapId])
        self.energyOnMap = json.loads(self.maps[self.mapId])
        for x in range(len(self.map)):
            for y in range(len(self.map[x])):
                if self.map[x][y] > 0:  # gold
                    self.energyOnMap[x][y] = -4
                else:  # obstacles
                    self.energyOnMap[x][y] = ObstacleInfo.types[self.map[x][y]]

    def connect(self): # simulate player's connect request
        print("Connected to server.")
        for mapid in range(len(Maps)):
            filename = "map" + str(mapid)
            print("Found: " + filename)
            self.maps[filename] = str(Maps[mapid])

    def map_info(self, map):  # get map info
        # print(map)
        userMatch = UserMatch()
        userMatch.gameinfo.height = len(map)
        userMatch.gameinfo.width = len(map[0])
        i = 0
        while i < len(map):
            j = 0
            while j < len(map[i]):
                if map[i][j] > 0:  # gold
                    g = GoldInfo()
                    g.posx = j
                    g.posy = i
                    g.amount = map[i][j]
                    userMatch.gameinfo.golds.append(g)
                else:  # obstacles
                    o = ObstacleInfo()
                    o.posx = j
                    o.posy = i
                    o.type = -map[i][j]
                    o.value = ObstacleInfo.types[map[i][j]]
                    userMatch.gameinfo.obstacles.append(o)
                j += 1
            i += 1
        return userMatch

    def receive(self):  # send data to player (simulate player's receive request)
        if self.resetFlag:  # for the first time -> send game info
            self.resetFlag = False
            data = self.userMatch.to_json()
            for (bot) in self.bots:
                bot.new_game(data)
            # print(data)
            return data
        else:  # send step state
            self.stepCount = self.stepCount + 1
            if self.stepCount >= self.maxStep:
                for player in self.stepState.players:
                    player.status = PlayerInfo.STATUS_STOP_END_STEP
            data = self.stepState.to_json()
            #for (bot) in self.bots:  # update bots' state
            for bot in self.bots:  # update bots' state
                bot.new_state(data)
            # print(data)
            return data

    def send(self, message):  # receive message from player (simulate send request from player)
        if message.isnumeric():  # player send action
            self.resetFlag = False
            self.stepState.changedObstacles = []
            action = int(message)
            # print("Action = ", action)
            self.user.lastAction = action
            self.craftUsers = []
            self.step_action(self.user, action)
            for bot in self.bots:
                if bot.info.status == PlayerInfo.STATUS_PLAYING:
                    action = bot.next_action()
                    bot.info.lastAction = action
                    # print("Bot Action: ", action)
                    self.step_action(bot.info, action)
            self.action_5_craft()
            for c in self.stepState.changedObstacles:
                self.map[c["posy"]][c["posx"]] = -c["type"]
                self.energyOnMap[c["posy"]][c["posx"]] = c["value"]

        else:  # reset game
            requests = message.split(",")
            #print("Reset game: ", requests[:3], end='')
            self.reset(requests)

    def step_action(self, user, action):
        switcher = {
            0: self.action_0_left,
            1: self.action_1_right,
            2: self.action_2_up,
            3: self.action_3_down,
            4: self.action_4_free,
            5: self.action_5_craft_pre
        }
        func = switcher.get(action, self.invalidAction)
        func(user)

    def action_5_craft_pre(self, user):  # collect players who craft at current step
        user.freeCount = 0
        if self.map[user.posy][user.posx] <= 0:  # craft at the non-gold cell
            user.energy -= 10
            if user.energy <= 0:
                user.status = PlayerInfo.STATUS_ELIMINATED_OUT_OF_ENERGY
                user.lastAction = 6 #eliminated
        else:
            user.energy -= 5
            if user.energy > 0:
                self.craftUsers.append(user)
                key = str(user.posx) + "_" + str(user.posy)
                if key in self.craftMap:
                    count = self.craftMap[key]
                    self.craftMap[key] = count + 1
                else:
                    self.craftMap[key] = 1
            else:
                user.status = PlayerInfo.STATUS_ELIMINATED_OUT_OF_ENERGY
                user.lastAction = 6 #eliminated

    def action_0_left(self, user):  # user go left
        user.freeCount = 0
        user.posx = user.posx - 1
        if user.posx < 0:
            user.status = PlayerInfo.STATUS_ELIMINATED_WENT_OUT_MAP
            user.lastAction = 6 #eliminated
        else:
            self.go_to_pos(user)

    def action_1_right(self, user):  # user go right
        user.freeCount = 0
        user.posx = user.posx + 1
        if user.posx >= self.userMatch.gameinfo.width:
            user.status = PlayerInfo.STATUS_ELIMINATED_WENT_OUT_MAP
            user.lastAction = 6 #eliminated
        else:
            self.go_to_pos(user)

    def action_2_up(self, user):  # user go up
        user.freeCount = 0
        user.posy = user.posy - 1
        if user.posy < 0:
            user.status = PlayerInfo.STATUS_ELIMINATED_WENT_OUT_MAP
            user.lastAction = 6 #eliminated
        else:
            self.go_to_pos(user)

    def action_3_down(self, user):  # user go right
        user.freeCount = 0
        user.posy = user.posy + 1
        if user.posy >= self.userMatch.gameinfo.height:
            user.status = PlayerInfo.STATUS_ELIMINATED_WENT_OUT_MAP
            user.lastAction = 6 #eliminated
        else:
            self.go_to_pos(user)

    def action_4_free(self, user):  # user free
        user.freeCount += 1
        if user.freeCount == 1:
            user.energy += int(self.E / 4)
        elif user.freeCount == 2:
            user.energy += int(self.E / 3)
        elif user.freeCount == 3:
            user.energy += int(self.E / 2)
        else:
            user.energy = self.E
        if user.energy > self.E:
            user.energy = self.E

    def action_5_craft(self):
        craftCount = len(self.craftUsers)
        # print ("craftCount",craftCount)
        if (craftCount > 0):
            for user in self.craftUsers:
                x = user.posx
                y = user.posy
                key = str(user.posx) + "_" + str(user.posy)
                c = self.craftMap[key]
                m = min(math.ceil(self.map[y][x] / c), 50)
                user.score += m
                # print ("user", user.playerId, m)
            for user in self.craftUsers:
                x = user.posx
                y = user.posy
                key = str(user.posx) + "_" + str(user.posy)
                if key in self.craftMap:
                    c = self.craftMap[key]
                    del self.craftMap[key]
                    m = min(math.ceil(self.map[y][x] / c), 50)
                    self.map[y][x] -= m * c
                    if self.map[y][x] < 0:
                        self.map[y][x] = 0
                        self.energyOnMap[y][x] = ObstacleInfo.types[0]
                    for g in self.stepState.golds:
                        if g.posx == x and g.posy == y:
                            g.amount = self.map[y][x]
                            if g.amount == 0:
                                self.stepState.golds.remove(g)
                                self.add_changed_obstacle(x, y, 0, ObstacleInfo.types[0])
                                if len(self.stepState.golds) == 0:
                                    for player in self.stepState.players:
                                        player.status = PlayerInfo.STATUS_STOP_EMPTY_GOLD
                            break;
            self.craftMap = {}

    def invalidAction(self, user):
        user.status = PlayerInfo.STATUS_ELIMINATED_INVALID_ACTION
        user.lastAction = 6 #eliminated

    def go_to_pos(self, user):  # player move to cell(x,y)
        if self.map[user.posy][user.posx] == -1:
            user.energy -= randrange(16) + 5
        elif self.map[user.posy][user.posx] == 0:
            user.energy += self.energyOnMap[user.posy][user.posx]
        elif self.map[user.posy][user.posx] == -2:
            user.energy += self.energyOnMap[user.posy][user.posx]
            self.add_changed_obstacle(user.posx, user.posy, 0, ObstacleInfo.types[0])
        elif self.map[user.posy][user.posx] == -3:
            user.energy += self.energyOnMap[user.posy][user.posx]
            self.add_changed_obstacle(user.posx, user.posy, 3,
                                      self.bog_energy_chain[self.energyOnMap[user.posy][user.posx]])
        else:
            user.energy -= 4
        if user.energy <= 0:
            user.status = PlayerInfo.STATUS_ELIMINATED_OUT_OF_ENERGY
            user.lastAction = 6 #eliminated

    def add_changed_obstacle(self, x, y, t, v):
        added = False
        for o in self.stepState.changedObstacles:
            if o["posx"] == x and o["posy"] == y:
                added = True
                break
        if added == False:
            o = {}
            o["posx"] = x
            o["posy"] = y
            o["type"] = t
            o["value"] = v
            self.stepState.changedObstacles.append(o)

    def close(self):
        print("Close socket.")

In [5]:
#Bots :bot1
class Bot1:
    ACTION_GO_LEFT = 0
    ACTION_GO_RIGHT = 1
    ACTION_GO_UP = 2
    ACTION_GO_DOWN = 3
    ACTION_FREE = 4
    ACTION_CRAFT = 5

    def __init__(self, id):
        self.state = State()
        self.info = PlayerInfo(id)

    def next_action(self):
        if self.state.mapInfo.gold_amount(self.info.posx, self.info.posy) > 0:
            if self.info.energy >= 6:
                return self.ACTION_CRAFT
            else:
                return self.ACTION_FREE
        if self.info.energy < 5:
            return self.ACTION_FREE
        else:
            action = self.ACTION_GO_UP
            if self.info.posy % 2 == 0:
                if self.info.posx < self.state.mapInfo.max_x:
                    action = self.ACTION_GO_RIGHT
            else:
                if self.info.posx > 0:
                    action = self.ACTION_GO_LEFT
                else:
                    action = self.ACTION_GO_DOWN
            return action

    def new_game(self, data):
        try:
            self.state.init_state(data)
        except Exception as e:
            import traceback
            traceback.print_exc()

    def new_state(self, data):
        # action = self.next_action();
        # self.socket.send(action)
        try:
            self.state.update_state(data)
        except Exception as e:
            import traceback
            traceback.print_exc()

In [6]:
#Bots :bot2
class Bot2:
    ACTION_GO_LEFT = 0
    ACTION_GO_RIGHT = 1
    ACTION_GO_UP = 2
    ACTION_GO_DOWN = 3
    ACTION_FREE = 4
    ACTION_CRAFT = 5

    def __init__(self, id):
        self.state = State()
        self.info = PlayerInfo(id)

    def next_action(self):
        if self.state.mapInfo.gold_amount(self.info.posx, self.info.posy) > 0:
            if self.info.energy >= 6:
                return self.ACTION_CRAFT
            else:
                return self.ACTION_FREE
        if self.info.energy < 5:
            return self.ACTION_FREE
        else:
            action = np.random.randint(0, 4)            
            return action

    def new_game(self, data):
        try:
            self.state.init_state(data)
        except Exception as e:
            import traceback
            traceback.print_exc()

    def new_state(self, data):
        # action = self.next_action();
        # self.socket.send(action)
        try:
            self.state.update_state(data)
        except Exception as e:
            import traceback
            traceback.print_exc()

In [7]:
#Bots :bot3
class Bot3:
    ACTION_GO_LEFT = 0
    ACTION_GO_RIGHT = 1
    ACTION_GO_UP = 2
    ACTION_GO_DOWN = 3
    ACTION_FREE = 4
    ACTION_CRAFT = 5

    def __init__(self, id):
        self.state = State()
        self.info = PlayerInfo(id)

    def next_action(self):
        if self.state.mapInfo.gold_amount(self.info.posx, self.info.posy) > 0:
            if self.info.energy >= 6:
                return self.ACTION_CRAFT
            else:
                return self.ACTION_FREE
        if self.info.energy < 5:
            return self.ACTION_FREE
        else:
            action = self.ACTION_GO_LEFT
            if self.info.posx % 2 == 0:
                if self.info.posy < self.state.mapInfo.max_y:
                    action = self.ACTION_GO_DOWN
            else:
                if self.info.posy > 0:
                    action = self.ACTION_GO_UP
                else:
                    action = self.ACTION_GO_RIGHT            
            return action

    def new_game(self, data):
        try:
            self.state.init_state(data)
        except Exception as e:
            import traceback
            traceback.print_exc()

    def new_state(self, data):
        # action = self.next_action();
        # self.socket.send(action)
        try:
            self.state.update_state(data)
        except Exception as e:
            import traceback
            traceback.print_exc()

In [8]:
#MinerState.py
def str_2_json(str):
    return json.loads(str, encoding="utf-8")


class MapInfo:
    def __init__(self):
        self.max_x = 0 #Width of the map
        self.max_y = 0 #Height of the map
        self.golds = [] #List of the golds in the map
        self.obstacles = []
        self.numberOfPlayers = 0
        self.maxStep = 0 #The maximum number of step is set for this map

    def init_map(self, gameInfo):
        #Initialize the map at the begining of each episode
        self.max_x = gameInfo["width"] - 1
        self.max_y = gameInfo["height"] - 1
        self.golds = gameInfo["golds"]
        self.obstacles = gameInfo["obstacles"]
        self.maxStep = gameInfo["steps"]
        self.numberOfPlayers = gameInfo["numberOfPlayers"]

    def update(self, golds, changedObstacles):
        #Update the map after every step
        self.golds = golds
        for cob in changedObstacles:
            newOb = True
            for ob in self.obstacles:
                if cob["posx"] == ob["posx"] and cob["posy"] == ob["posy"]:
                    newOb = False
                    #print("cell(", cob["posx"], ",", cob["posy"], ") change type from: ", ob["type"], " -> ",
                    #      cob["type"], " / value: ", ob["value"], " -> ", cob["value"])
                    ob["type"] = cob["type"]
                    ob["value"] = cob["value"]
                    break
            if newOb:
                self.obstacles.append(cob)
                #print("new obstacle: ", cob["posx"], ",", cob["posy"], ", type = ", cob["type"], ", value = ",
                #      cob["value"])

    def get_min_x(self):
        return min([cell["posx"] for cell in self.golds])

    def get_max_x(self):
        return max([cell["posx"] for cell in self.golds])

    def get_min_y(self):
        return min([cell["posy"] for cell in self.golds])

    def get_max_y(self):
        return max([cell["posy"] for cell in self.golds])

    def is_row_has_gold(self, y):
        return y in [cell["posy"] for cell in self.golds]

    def is_column_has_gold(self, x):
        return x in [cell["posx"] for cell in self.golds]

    def gold_amount(self, x, y): #Get the amount of golds at cell (x,y)
        for cell in self.golds:
            if x == cell["posx"] and y == cell["posy"]:
                return cell["amount"]
        return 0 

    def get_obstacle(self, x, y):  # Get the kind of the obstacle at cell(x,y)
        for cell in self.obstacles:
            if x == cell["posx"] and y == cell["posy"]:
                return cell["type"]
        return -1  # No obstacle at the cell (x,y)


class State:
    STATUS_PLAYING = 0
    STATUS_ELIMINATED_WENT_OUT_MAP = 1
    STATUS_ELIMINATED_OUT_OF_ENERGY = 2
    STATUS_ELIMINATED_INVALID_ACTION = 3
    STATUS_STOP_EMPTY_GOLD = 4
    STATUS_STOP_END_STEP = 5

    def __init__(self):
        self.end = False
        self.score = 0
        self.lastAction = None
        self.id = 0
        self.x = 0
        self.y = 0
        self.energy = 0
        self.mapInfo = MapInfo()
        self.players = []
        self.stepCount = 0
        self.status = State.STATUS_PLAYING

    def init_state(self, data): #parse data from server into object
        game_info = str_2_json(data)
        self.end = False
        self.score = 0
        self.lastAction = None
        self.id = game_info["playerId"]
        self.x = game_info["posx"]
        self.y = game_info["posy"]
        self.energy = game_info["energy"]
        self.mapInfo.init_map(game_info["gameinfo"])
        self.stepCount = 0
        self.status = State.STATUS_PLAYING
        self.players = [{"playerId": 2, "posx": self.x, "posy": self.y},
                        {"playerId": 3, "posx": self.x, "posy": self.y},
                        {"playerId": 4, "posx": self.x, "posy": self.y}]

    def update_state(self, data):
        new_state = str_2_json(data)
        for player in new_state["players"]:
            if player["playerId"] == self.id:
                self.x = player["posx"]
                self.y = player["posy"]
                self.energy = player["energy"]
                self.score = player["score"]
                self.lastAction = player["lastAction"]
                self.status = player["status"]

        self.mapInfo.update(new_state["golds"], new_state["changedObstacles"])
        self.players = new_state["players"]
        for i in range(len(self.players), 4, 1):
            self.players.append({"playerId": i, "posx": self.x, "posy": self.y})
        self.stepCount = self.stepCount + 1

In [9]:
#MinerEnv.py
TreeID = 1
TrapID = 2
SwampID = 3
class MinerEnv:
    def __init__(self):
        self.socket = GameSocket()
        self.state = State()
        
        self.score_pre = self.state.score#Storing the last score for designing the reward function

    def start(self): #connect to server
        self.socket.connect()

    def end(self): #disconnect server
        self.socket.close()

    def send_map_info(self, request):#tell server which map to run
        self.socket.send(request)

    def reset(self): #start new game
        try:
            message = self.socket.receive() #receive game info from server
            self.state.init_state(message) #init state
        except Exception as e:
            import traceback
            traceback.print_exc()

    def step(self, action): #step process
        self.socket.send(action) #send action to server
        try:
            message = self.socket.receive() #receive new state from server
            self.state.update_state(message) #update to local state
        except Exception as e:
            import traceback
            traceback.print_exc()

    # Functions are customized by client
    def get_state(self):
        # Building the map
        #view = np.zeros([self.state.mapInfo.max_x + 1, self.state.mapInfo.max_y + 1], dtype=int)
        view = np.zeros([self.state.mapInfo.max_y + 1, self.state.mapInfo.max_x + 1], dtype=int)
        for x in range(self.state.mapInfo.max_x + 1):
            for y in range(self.state.mapInfo.max_y + 1):
                if self.state.mapInfo.get_obstacle(x, y) == TreeID:  # Tree
                    view[y, x] = -TreeID
                if self.state.mapInfo.get_obstacle(x, y) == TrapID:  # Trap
                    view[y, x] = -TrapID
                if self.state.mapInfo.get_obstacle(x, y) == SwampID: # Swamp
                    view[y, x] = -SwampID
                if self.state.mapInfo.gold_amount(x, y) > 0:
                    view[y, x] = self.state.mapInfo.gold_amount(x, y)

        DQNState = view.flatten().tolist() #Flattening the map matrix to a vector
        
        # Add position and energy of agent to the DQNState
        DQNState.append(self.state.x)
        DQNState.append(self.state.y)
        DQNState.append(self.state.energy)
        #Add position of bots 
        for player in self.state.players:
            if player["playerId"] != self.state.id:
                DQNState.append(player["posx"])
                DQNState.append(player["posy"])
                
        #Convert the DQNState from list to array for training
        DQNState = np.array(DQNState)

        return DQNState

    def get_reward(self):
        # Initialize reward
        reward = 0
        score_action = self.state.score - self.score_pre
        self.score_pre = self.state.score
        if score_action > 0:
            reward += score_action*(100 - self.state.stepCount)
            
        ##If the DQN agent crashs into obstacels (Tree, Trap, Swamp), then it should be punished by a negative reward
        #if self.state.mapInfo.get_obstacle(self.state.x, self.state.y) == TreeID:  # Tree
        #    reward -= TreeID
        #if self.state.mapInfo.get_obstacle(self.state.x, self.state.y) == TrapID:  # Trap
        #    reward -= TrapID
        #if self.state.mapInfo.get_obstacle(self.state.x, self.state.y) == SwampID:  # Swamp
        #    reward -= SwampID
        #    if self.state.lastAction == 4:
        #        reward -= 40

        # If out of the map, then the DQN agent should be punished by a larger nagative reward.
        if self.state.status == State.STATUS_ELIMINATED_WENT_OUT_MAP:
            #if self.state.stepCount < 50:
            #    reward += -5*(50 - self.state.stepCount)
            reward = 0
            
        if self.state.status == State.STATUS_STOP_END_STEP:
            #reward += (self.state.score/total_gold) * 100
            pass
        #Run out of energy, then the DQN agent should be punished by a larger nagative reward.
        if self.state.status == State.STATUS_ELIMINATED_OUT_OF_ENERGY:
            if self.state.lastAction != int(constants.available_actions["rest"]):
                # Unless it is the last step and dig was more urgent
                reward = 0
        
        ## control comes to here \implies our agent is not dead yet
        if self.state.status == State.STATUS_PLAYING:
            if self.state.energy > 40 and self.state.lastAction == int(constants.available_actions["rest"]):
                reward = 1
            else:
                reward += 1
        ## print ("reward",reward)
        return reward

    def check_terminate(self):
        #Checking the status of the game
        #it indicates the game ends or is playing
        return self.state.status != State.STATUS_PLAYING

In [10]:
# Maps of 1st round
def CreateMaps():
    map0 = [
      [450,-2,0,-2,150,-1,0,0,0,0,-1,-2,-2,-2,0,0,0,0,150,-2,350],
      [-2,-2,-2,-2,-1,0,-1,-1,-1,-1,-3,50,-2,-2,-2,-2,-3,-3,50,-2,-1],
      [-2,-2,200,-2,0,-2,0,-2,-3,-3,-2,0,-3,-2,-2,150,-3,-3,0,0,50],
      [0,-3,-3,-2,0,0,-1,0,550,-3,-2,0,0,0,-1,0,0,-1,-1,-1,-2],
      [-2,0,0,0,-1,0,-1,50,300,-3,-2,0,-3,0,0,0,-1,-3,-3,-2,-1],
      [-1,-3,-1,-3,0,-2,0,0,-2,-1,100,-3,0,-2,300,-3,0,-2,-3,-2,0],
      [-2,-3,-1,-3,-1,500,-1,-3,-2,-1,0,-1,0,-1,0,-1,0,-2,-3,-3,-1],
      [0,-3,-1,-3,0,-2,-3,-3,0,0,0,0,-2,0,-2,-3,-3,-3,-3,200,-1],
      [1200,-3,-1,-3,-1,-1,-2,-2,0,-1,150,-2,0,-2,0,0,-2,-3,-3,1500,50],
    ]
    map1 = [
      [550,-1,-1,-2,-2,-2,-2,150,0,0,0,-3,-2,400,-3,650,-2,-1,0,0,0],
      [350,-1,-1,-2,0,0,-2,-2,-2,-1,0,-3,-3,-2,300,-2,-1,650,-2,-1,0],
      [-1,-1,450,-2,0,0,0,0,0,0,0,0,0,-3,-3,-3,-1,-1,-3,0,0],
      [-1,-1,-2,-2,0,-3,-2,0,0,-3,-3,-3,0,0,0,0,0,0,-3,0,150],
      [0,0,-2,0,-3,-3,-3,0,-1,-2,400,-3,-3,0,-2,0,-1,0,-3,0,0],
      [0,200,-2,0,-3,250,-1,0,0,-1,-2,-3,-2,0,-1,300,-1,0,-3,-1,0],
      [-3,-3,-2,0,-3,-3,-3,0,0,0,0,-3,-3,-3,-2,-2,-2,0,-2,-2,0],
      [-1,-3,-2,0,0,-2,0,0,-3,-3,-3,-3,150,-3,0,0,0,0,-2,200,0],
      [800,-3,-2,-3,450,-2,0,-3,-3,200,-1,250,-1,-3,0,-1,-1,0,0,0,0],
    ]
    map2 = [
      [200,-2,-2,250,-2,0,-2,-1,0,-3,500,-3,-3,0,0,0,0,0,-3,450,-3],
      [-2,-2,-1,-2,-1,0,-3,200,-2,0,-3,0,150,0,-2,-1,0,0,0,-3,0],
      [-3,-2,-1,-3,-1,0,0,-3,-2,0,0,0,-1,-2,450,-2,0,-2,150,-2,0],
      [300,-3,-3,300,-2,-2,-2,-2,300,-2,-2,0,0,0,-2,0,-3,-3,-3,-2,0],
      [-3,-3,0,-3,-1,350,-1,0,-2,-2,350,-2,0,-3,0,0,-3,300,-3,-2,250],
      [-3,0,0,0,-1,-1,-1,-1,-3,0,-2,0,-3,400,-3,0,-3,-3,-3,0,0],
      [450,-3,0,0,0,0,-1,400,-3,0,0,0,-2,-3,-2,0,0,0,0,0,0],
      [-3,0,-1,0,-1,0,-3,-3,-3,0,-1,0,0,0,250,-3,-3,-3,-1,-2,-2],
      [0,0,-1,200,-1,-3,500,-3,0,-1,200,-1,0,0,-2,-2,-2,-1,400,-1,-2],
    ]
    map3 = [
      [0,-1,0,0,0,0,0,-3,0,-1,0,-1,-3,150,500,200,-1,0,-2,-1,0],
      [-3,500,-3,-2,350,-1,0,0,0,0,0,0,-1,-1,50,-1,0,0,-2,350,-3],
      [-1,-3,-2,0,-1,-2,0,-1,0,0,0,0,0,0,-2,-1,0,0,-2,-1,-3],
      [0,-3,0,0,0,0,-2,600,-3,0,0,-2,-2,0,-2,0,0,0,0,0,0],
      [0,0,0,0,-1,-1,0,-3,0,-1,400,-3,-2,0,0,0,-1,-2,-1,-1,-1],
      [-1,0,0,-1,-3,-3,-1,-1,0,0,-3,-2,0,0,0,0,-1,700,-1,-1,-3],
      [350,-2,-1,-3,-2,-3,-3,-1,0,-3,0,0,0,0,-3,0,-1,-1,-1,-3,200],
      [0,-1,-3,-2,250,-2,-3,-1,0,0,0,0,-2,0,0,0,0,-1,-3,300,0],
      [0,-3,-2,300,1000,-2,-3,-1,0,-1,0,-2,100,-2,-1,0,-1,-3,400,0,800],
    ]
    map4 = [
      [0,0,0,0,0,0,0,-2,0,0,0,0,-2,0,0,0,0,-1,-1,800,-1],
      [100,-1,-3,-2,0,0,-1,200,-1,-2,250,-2,-2,250,-1,0,0,-1,-2,-1,-2],
      [-1,700,-1,-3,150,-1,-1,-3,-3,-2,-2,-1,-3,-2,-1,0,0,-3,0,-1,0],
      [0,-1,-3,0,-1,0,-3,-3,-1,-3,-1,600,-1,-3,-2,-1,-3,500,-1,0,0],
      [0,-3,0,0,0,0,-2,-1,350,-1,50,-1,-3,50,0,0,0,-1,0,0,-2],
      [0,0,0,-3,250,-3,-3,-3,-1,500,450,-1,-3,0,-1,0,0,0,0,-2,100],
      [0,-3,0,0,-3,0,0,0,-3,-1,-1,-3,0,0,-2,300,-2,-1,0,0,-2],
      [0,-1,-3,-2,0,0,0,-1,0,-3,-3,-3,-1,-2,-2,-1,-2,0,-1,0,0],
      [-1,500,-1,-3,-2,0,-1,450,-1,0,0,-1,500,-1,-2,-1,-2,0,50,0,0],
    ]
    Maps = (map0,map1,map2,map3,map4)
    return Maps

In [11]:
Maps = CreateMaps()
env = MinerEnv() # Creating a communication environment between the DQN model and the game environment
env.start() # Connect to the game

Connected to server.
Found: map0
Found: map1
Found: map2
Found: map3
Found: map4


There is sth called <code><b>GameSocket.energyOnMap</b></code> in the design of this gaming environment, which is of the same shape as the map view and which records the number that should be subtracted from the energy of a particular player in case they step into the coordinate (x, y). 


In [12]:
env.socket.energyOnMap

[]

In [13]:
type(env.socket.energyOnMap)

list

In [14]:
np.array(env.socket.energyOnMap)

array([], dtype=float64)

In [15]:
mapID = np.random.randint(0, 5)
posID_x = np.random.randint(constants.width) 
posID_y = np.random.randint(constants.height)
request = "map{},{},{},50,100".format(mapID, posID_x, posID_y)
print(request)
env.send_map_info(request)
#obs = env.reset()
env.reset()

map3,10,2,50,100


In [16]:
env.socket.energyOnMap

[[-1,
  0,
  -1,
  -1,
  -1,
  -1,
  -1,
  -5,
  -1,
  0,
  -1,
  0,
  -5,
  -4,
  -4,
  -4,
  0,
  -1,
  -10,
  0,
  -1],
 [-5,
  -4,
  -5,
  -10,
  -4,
  0,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  0,
  0,
  -4,
  0,
  -1,
  -1,
  -10,
  -4,
  -5],
 [0,
  -5,
  -10,
  -1,
  0,
  -10,
  -1,
  0,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1,
  -10,
  0,
  -1,
  -1,
  -10,
  0,
  -5],
 [-1,
  -5,
  -1,
  -1,
  -1,
  -1,
  -10,
  -4,
  -5,
  -1,
  -1,
  -10,
  -10,
  -1,
  -10,
  -1,
  -1,
  -1,
  -1,
  -1,
  -1],
 [-1,
  -1,
  -1,
  -1,
  0,
  0,
  -1,
  -5,
  -1,
  0,
  -4,
  -5,
  -10,
  -1,
  -1,
  -1,
  0,
  -10,
  0,
  0,
  0],
 [0,
  -1,
  -1,
  0,
  -5,
  -5,
  0,
  0,
  -1,
  -1,
  -5,
  -10,
  -1,
  -1,
  -1,
  -1,
  0,
  -4,
  0,
  0,
  -5],
 [-4,
  -10,
  0,
  -5,
  -10,
  -5,
  -5,
  0,
  -1,
  -5,
  -1,
  -1,
  -1,
  -1,
  -5,
  -1,
  0,
  0,
  0,
  -5,
  -4],
 [-1,
  0,
  -5,
  -10,
  -4,
  -10,
  -5,
  0,
  -1,
  -1,
  -1,
  -1,
  -10,
  -1,
  -1,
  -1,
  -1,
  0,
  -5,
  -4,
  -1],
 

In [17]:
type(env.socket.energyOnMap)

list

In [18]:
np.array(env.socket.energyOnMap)

array([[ -1,   0,  -1,  -1,  -1,  -1,  -1,  -5,  -1,   0,  -1,   0,  -5,
         -4,  -4,  -4,   0,  -1, -10,   0,  -1],
       [ -5,  -4,  -5, -10,  -4,   0,  -1,  -1,  -1,  -1,  -1,  -1,   0,
          0,  -4,   0,  -1,  -1, -10,  -4,  -5],
       [  0,  -5, -10,  -1,   0, -10,  -1,   0,  -1,  -1,  -1,  -1,  -1,
         -1, -10,   0,  -1,  -1, -10,   0,  -5],
       [ -1,  -5,  -1,  -1,  -1,  -1, -10,  -4,  -5,  -1,  -1, -10, -10,
         -1, -10,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1,   0,   0,  -1,  -5,  -1,   0,  -4,  -5, -10,
         -1,  -1,  -1,   0, -10,   0,   0,   0],
       [  0,  -1,  -1,   0,  -5,  -5,   0,   0,  -1,  -1,  -5, -10,  -1,
         -1,  -1,  -1,   0,  -4,   0,   0,  -5],
       [ -4, -10,   0,  -5, -10,  -5,  -5,   0,  -1,  -5,  -1,  -1,  -1,
         -1,  -5,  -1,   0,   0,   0,  -5,  -4],
       [ -1,   0,  -5, -10,  -4, -10,  -5,   0,  -1,  -1,  -1,  -1, -10,
         -1,  -1,  -1,  -1,   0,  -5,  -4,  -1],
       [ -1,  -5, -10,  

In [19]:
np.array(env.socket.energyOnMap).shape

(9, 21)

In [20]:
import constants
env.get_state()[:constants.n_px].reshape((9,21))

array([[   0,   -1,    0,    0,    0,    0,    0,   -3,    0,   -1,    0,
          -1,   -3,  150,  500,  200,   -1,    0,   -2,   -1,    0],
       [  -3,  500,   -3,   -2,  350,   -1,    0,    0,    0,    0,    0,
           0,   -1,   -1,   50,   -1,    0,    0,   -2,  350,   -3],
       [  -1,   -3,   -2,    0,   -1,   -2,    0,   -1,    0,    0,    0,
           0,    0,    0,   -2,   -1,    0,    0,   -2,   -1,   -3],
       [   0,   -3,    0,    0,    0,    0,   -2,  600,   -3,    0,    0,
          -2,   -2,    0,   -2,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,   -1,   -1,    0,   -3,    0,   -1,  400,
          -3,   -2,    0,    0,    0,   -1,   -2,   -1,   -1,   -1],
       [  -1,    0,    0,   -1,   -3,   -3,   -1,   -1,    0,    0,   -3,
          -2,    0,    0,    0,    0,   -1,  700,   -1,   -1,   -3],
       [ 350,   -2,   -1,   -3,   -2,   -3,   -3,   -1,    0,   -3,    0,
           0,    0,    0,   -3,    0,   -1,   -1,   -1,   -3,  200],

In [21]:
E = np.array(env.socket.energyOnMap)
A = env.get_state()[:constants.n_px].reshape((9,21))

In [22]:
forest_subtract = 20

In [23]:
E_forest = E.copy()
E_forest[E==0] = -forest_subtract
E_forest

array([[ -1, -20,  -1,  -1,  -1,  -1,  -1,  -5,  -1, -20,  -1, -20,  -5,
         -4,  -4,  -4, -20,  -1, -10, -20,  -1],
       [ -5,  -4,  -5, -10,  -4, -20,  -1,  -1,  -1,  -1,  -1,  -1, -20,
        -20,  -4, -20,  -1,  -1, -10,  -4,  -5],
       [-20,  -5, -10,  -1, -20, -10,  -1, -20,  -1,  -1,  -1,  -1,  -1,
         -1, -10, -20,  -1,  -1, -10, -20,  -5],
       [ -1,  -5,  -1,  -1,  -1,  -1, -10,  -4,  -5,  -1,  -1, -10, -10,
         -1, -10,  -1,  -1,  -1,  -1,  -1,  -1],
       [ -1,  -1,  -1,  -1, -20, -20,  -1,  -5,  -1, -20,  -4,  -5, -10,
         -1,  -1,  -1, -20, -10, -20, -20, -20],
       [-20,  -1,  -1, -20,  -5,  -5, -20, -20,  -1,  -1,  -5, -10,  -1,
         -1,  -1,  -1, -20,  -4, -20, -20,  -5],
       [ -4, -10, -20,  -5, -10,  -5,  -5, -20,  -1,  -5,  -1,  -1,  -1,
         -1,  -5,  -1, -20, -20, -20,  -5,  -4],
       [ -1, -20,  -5, -10,  -4, -10,  -5, -20,  -1,  -1,  -1,  -1, -10,
         -1,  -1,  -1,  -1, -20,  -5,  -4,  -1],
       [ -1,  -5, -10,  

In [25]:
A_gold = A.copy()
A_gold[A <= 0] = -9999
A_gold

array([[-9999, -9999, -9999, -9999, -9999, -9999, -9999, -9999, -9999,
        -9999, -9999, -9999, -9999,   150,   500,   200, -9999, -9999,
        -9999, -9999, -9999],
       [-9999,   500, -9999, -9999,   350, -9999, -9999, -9999, -9999,
        -9999, -9999, -9999, -9999, -9999,    50, -9999, -9999, -9999,
        -9999,   350, -9999],
       [-9999, -9999, -9999, -9999, -9999, -9999, -9999, -9999, -9999,
        -9999, -9999, -9999, -9999, -9999, -9999, -9999, -9999, -9999,
        -9999, -9999, -9999],
       [-9999, -9999, -9999, -9999, -9999, -9999, -9999,   600, -9999,
        -9999, -9999, -9999, -9999, -9999, -9999, -9999, -9999, -9999,
        -9999, -9999, -9999],
       [-9999, -9999, -9999, -9999, -9999, -9999, -9999, -9999, -9999,
        -9999,   400, -9999, -9999, -9999, -9999, -9999, -9999, -9999,
        -9999, -9999, -9999],
       [-9999, -9999, -9999, -9999, -9999, -9999, -9999, -9999, -9999,
        -9999, -9999, -9999, -9999, -9999, -9999, -9999, -9999,   700

In [28]:
res = np.maximum(A_gold, E_forest)
res

array([[  -1,  -20,   -1,   -1,   -1,   -1,   -1,   -5,   -1,  -20,   -1,
         -20,   -5,  150,  500,  200,  -20,   -1,  -10,  -20,   -1],
       [  -5,  500,   -5,  -10,  350,  -20,   -1,   -1,   -1,   -1,   -1,
          -1,  -20,  -20,   50,  -20,   -1,   -1,  -10,  350,   -5],
       [ -20,   -5,  -10,   -1,  -20,  -10,   -1,  -20,   -1,   -1,   -1,
          -1,   -1,   -1,  -10,  -20,   -1,   -1,  -10,  -20,   -5],
       [  -1,   -5,   -1,   -1,   -1,   -1,  -10,  600,   -5,   -1,   -1,
         -10,  -10,   -1,  -10,   -1,   -1,   -1,   -1,   -1,   -1],
       [  -1,   -1,   -1,   -1,  -20,  -20,   -1,   -5,   -1,  -20,  400,
          -5,  -10,   -1,   -1,   -1,  -20,  -10,  -20,  -20,  -20],
       [ -20,   -1,   -1,  -20,   -5,   -5,  -20,  -20,   -1,   -1,   -5,
         -10,   -1,   -1,   -1,   -1,  -20,  700,  -20,  -20,   -5],
       [ 350,  -10,  -20,   -5,  -10,   -5,   -5,  -20,   -1,   -5,   -1,
          -1,   -1,   -1,   -5,   -1,  -20,  -20,  -20,   -5,  200],

In [ ]:
obs = env.get_state()
print(f"obs[9*21:] = {obs[9*21:]}")
obs[:9*21].reshape((9,21))

In [ ]:
eliminated = []
def pictorial_state(obs):
    pictorial = np.zeros((constants.height, constants.width, 1+4), dtype=np.float32)
    # 1+4 is +1 for map and +1 for each of the players = 5 channels
    # dtype=np.float32 because pictorial will later be carried into tensorflow CNN
    pictorial[..., 0] = obs[:constants.n_px].reshape((constants.height, constants.width))
    # position of agent: we put the energy value at the coordinate where stands the agent, the whole in channel 1, the channel for the agent.
    x_agent, y_agent = obs[constants.n_px], obs[constants.n_px+1]
    if x_agent >= constants.width or y_agent >= constants.height:
        pass
    else:
        pictorial[y_agent, x_agent, 1] = obs[constants.n_px+2]
    # position of bots: we put -1 on the coord of the bots
    for i in range(1, 3+1):
        if i in eliminated:
            continue
        y = obs[constants.n_px+(2*i+2)]
        x = obs[constants.n_px+(2*i+1)]
        if x >= constants.width or y >= constants.height:
            eliminated.append(i)
            continue
        pictorial[y, x, i+1] = -1
    return pictorial

In [ ]:
obs[constants.n_px:]

In [ ]:
pix = pictorial_state(obs)
pix[...,0]

In [ ]:
pix[...,1]

In [ ]:
pix[...,-1]

In [ ]:
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Dropout, Flatten

In [ ]:
#tf.random.set_seed(42)
np.random.seed(42)

input_shape = [constants.height, constants.width, 1+4]
n_outputs = 6

#model = keras.models.Sequential([
#    Conv2D(64, 3, activation="relu", padding="same", input_shape=input_shape),
#    MaxPooling2D(2),
#    Conv2D(128, 3, activation="relu", padding="same"),
#    Conv2D(128, 3, activation="relu", padding="same"),
#    MaxPooling2D(2),
#    Flatten(),
#    Dense(128, activation="elu"),
#    Dense(128, activation="elu"),
#    Dense(128, activation="elu"),
#    Dense(64, activation="elu"),
#    Dense(n_outputs)
#])

model = keras.models.load_model("never_out_map.h5")

In [ ]:
max_replay_len = 2000

In [ ]:
from collections import deque
replay_memory = deque(maxlen=max_replay_len)

In [ ]:
def sample_experiences(batch_size):
    indices = np.random.randint(len(replay_memory), size=batch_size)
    batch = [replay_memory[index] for index in indices]
    states, actions, rewards, next_states, dones = [
        np.array([experience[field_index] for experience in batch])
        for field_index in range(5)]
    return states, actions, rewards, next_states, dones

In [ ]:
def epsilon_greedy_policy(state, epsilon=0, n_actions=6):
    if np.random.rand() < epsilon:
        return np.random.randint(n_actions)
    else:
        pictorial = pictorial_state(state)
        Q_values = model.predict(pictorial[np.newaxis])
        return np.argmax(Q_values[0])

In [ ]:
def play_one_step(env, state, epsilon):
    action = epsilon_greedy_policy(state, epsilon)
    #next_state, reward, done, info = env.step(action)
    env.step(str(action))
    next_state = env.get_state()
    reward = env.get_reward()
    done = env.check_terminate()
    replay_memory.append((state, action, reward, next_state, done))
    return next_state, reward, done

In [ ]:
batch_size = 32
discount_rate = 0.95
optimizer = keras.optimizers.Adam(lr=1e-3)
loss_fn = keras.losses.mean_squared_error

def training_step(batch_size):
    experiences = sample_experiences(batch_size)
    states, actions, rewards, next_states, dones = experiences
    pictorials = np.array([pictorial_state(s) for s in states])
    next_pictorials = np.array([pictorial_state(next_s) for next_s in next_states])
    next_Q_values = model.predict(next_pictorials)
    max_next_Q_values = np.max(next_Q_values, axis=1)
    target_Q_values = rewards + (1 - dones) * discount_rate * max_next_Q_values
    mask = tf.one_hot(actions, n_outputs)
    with tf.GradientTape() as tape:
        #all_Q_values = model(states)
        all_Q_values = model(pictorials)
        Q_values = tf.reduce_sum(all_Q_values * mask, axis=1, keepdims=True)
        loss = tf.reduce_mean(loss_fn(target_Q_values, Q_values))
    grads = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))

In [ ]:
#env.seed(42)
np.random.seed(42)
#tf.random.set_seed(42)

scores = [] 
best_score = 0

In [ ]:
n_episodes = 10_000
n_epsilon_decay = int(n_episodes*.7)
n_max_steps = 100

for episode in range(n_episodes):
    eliminated = []
    mapID = np.random.randint(0, 5)
    posID_x = np.random.randint(constants.width) 
    posID_y = np.random.randint(constants.height)
    request = "map{},{},{},50,100".format(mapID, posID_x, posID_y)
    env.send_map_info(request)
    #obs = env.reset()
    env.reset()
    obs = env.get_state()
    sum_reward = 0
    for step in range(n_max_steps):
        epsilon = max(1 - episode / n_epsilon_decay, 0.01)
        obs, reward, done = play_one_step(env, obs, epsilon)
        sum_reward += reward
        if done:
            break
    score = env.state.score*(n_max_steps - step)
    #scores.append(score)
    if score > best_score:
        best_weights = model.get_weights()
        best_score = reward
    #print("\rEpisode: {}, Steps: {}, eps: {:.3f}".format(episode, step + 1, epsilon), end="")
    #print("Episode: {: 5d}, Gold: {: 4d}, Steps: {: 3d}, eps: {:.3f}. ({})".format(episode, env.state.score, step + 1, epsilon, game_over_reason[env.state.status]), end="\n\n")
    #print("(Episode: {: 5d})   Gold: {: 4d}, Steps: {: 3d}, eps: {:.3f}. ({})".format(episode, env.state.score, step + 1, epsilon, game_over_reason[env.state.status]))
    print("(Episode {: 5d})   Gold: {: 4d}  sum_reward: {: 6d}   Steps: {: 3d}   eps: {:.3f}  ({})".format(episode, env.state.score, sum_reward, step + 1, epsilon, game_over_reason[env.state.status]))

    #if episode > 1000:
    if episode > 500:
        training_step(batch_size)

model.set_weights(best_weights)

In [ ]:
n_episodes = 10_000
n_epsilon_decay = int(n_episodes*.7)
n_max_steps = 100

for episode in range(n_episodes):
    eliminated = []
    mapID = np.random.randint(0, 5)
    posID_x = np.random.randint(constants.width) 
    posID_y = np.random.randint(constants.height)
    request = "map{},{},{},50,100".format(mapID, posID_x, posID_y)
    env.send_map_info(request)
    #obs = env.reset()
    env.reset()
    obs = env.get_state()
    sum_reward = 0
    for step in range(n_max_steps):
        epsilon = max(1 - episode / n_epsilon_decay, 0.01)
        obs, reward, done = play_one_step(env, obs, epsilon)
        sum_reward += reward
        if done:
            break
    score = env.state.score*(n_max_steps - step)
    #scores.append(score)
    if score > best_score:
        best_weights = model.get_weights()
        best_score = reward
    #print("\rEpisode: {}, Steps: {}, eps: {:.3f}".format(episode, step + 1, epsilon), end="")
    #print("Episode: {: 5d}, Gold: {: 4d}, Steps: {: 3d}, eps: {:.3f}. ({})".format(episode, env.state.score, step + 1, epsilon, game_over_reason[env.state.status]), end="\n\n")
    #print("(Episode: {: 5d})   Gold: {: 4d}, Steps: {: 3d}, eps: {:.3f}. ({})".format(episode, env.state.score, step + 1, epsilon, game_over_reason[env.state.status]))
    print("(Episode {: 5d})   Gold: {: 4d},  sum_reward: {: 6d}, Steps: {: 3d}, eps: {:.3f}. ({})".format(episode, env.state.score, sum_reward, step + 1, epsilon, game_over_reason[env.state.status]))

    if episode > 1000:
        training_step(batch_size)

model.set_weights(best_weights)